### ISSUE TITLE
Controller Testing (2024)

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/software-projects#7]
# [S-7] Controller Testing (2024)
## Description
We need to perform physical bench testing of our controllers before competition 2024.

## Tasks
- [ ] Determine test procedure for controllers
- [ ] Test drivetrain controller
- [ ] Test display controller
- [ ] Test PID controller (maybe)
- [ ] Create a formal test results document for 2024

## Linked Issues
-
